#!/bin/bash
#echo < quote | tr 'N-ZA-Mn-za-m' 'A-Za-z' | tr 'A-Za-z' 'N-ZA-Mn-za-m'
tr `echo {a..z} | tr -d ' '` `echo {n..z} $(echo {a..m}) | tr -d ' '` | tr `echo {A..Z} | tr -d ' '` `echo {N..Z} $(echo {A..M}) | tr -d ' '`
